import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
const source=readFileSync(new URL('../sw.js',import.meta.url),'utf8');
function fixture(){const handlers={},deleted=[],writes=[],cached=new Map();const current='raptor-shell-v1.8.0';const env={self:{addEventListener:(n,fn)=>handlers[n]=fn,clients:{claim:async()=>{}},skipWaiting:async()=>{}},caches:{keys:async()=>['another-app-cache','raptor-shell-v1',current],delete:async k=>deleted.push(k),open:async()=>({match:async k=>cached.get(k),put:async(k,v)=>writes.push(k)})},fetch:async()=>{throw Error('offline')},location:{origin:'https://raptor.test'},URL,Response};runInNewContext(source,env);return {handlers,deleted,writes,cached,env};}
test('activation retires only older RAPTOR caches',async()=>{const f=fixture();let work;f.handlers.activate({waitUntil:p=>work=p});await work;assert.deepEqual(f.deleted,['raptor-shell-v1']);});
test('an offline query link uses the current shell while uncached modules fail as network errors',async()=>{const f=fixture();const shell=new Response('shell');f.cached.set('/',shell);let response;f.handlers.fetch({request:{method:'GET',url:'https://raptor.test/?mode=practice'},respondWith:p=>response=p});assert.equal(await response,shell);f.handlers.fetch({request:{method:'GET',url:'https://raptor.test/src/main.js'},respondWith:p=>response=p});assert.equal((await response).type,'error');});
test('network shell refreshes are retained for worker lifetime and normalized by path',async()=>{const f=fixture();f.env.fetch=async()=>new Response('fresh');let response,work;f.handlers.fetch({request:{method:'GET',url:'https://raptor.test/?mode=practice'},respondWith:p=>response=p,waitUntil:p=>work=p});assert.equal(await (await response).text(),'fresh');await work;assert.deepEqual(f.writes,['/']);});
